// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolHubApi.Data;

#nullable disable

namespace SchoolHubApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260923123503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolHubApi.Models.AuthModels.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageGrade")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageGrade")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.StudentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentReports");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageGrade")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.TeacherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherReports");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsHomework")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherUserId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("SchoolHubApi.Models.UserModels.TeacherUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeacherUsers");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Classroom", b =>
                {
                    b.HasOne("SchoolHubApi.Models.UserModels.TeacherUser", null)
                        .WithMany("Classrooms")
                        .HasForeignKey("TeacherUserId");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Mark", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolHubApi.Models.SchoolModels.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.School", b =>
                {
                    b.HasOne("SchoolHubApi.Models.UserModels.TeacherUser", null)
                        .WithMany("Schools")
                        .HasForeignKey("TeacherUserId");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Student", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.StudentReport", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Student", null)
                        .WithMany("Reports")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Subject", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolHubApi.Models.SchoolModels.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.TeacherReport", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Teacher", null)
                        .WithMany("Reports")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Work", b =>
                {
                    b.HasOne("SchoolHubApi.Models.SchoolModels.Subject", null)
                        .WithMany("Works")
                        .HasForeignKey("SubjectId");

                    b.HasOne("SchoolHubApi.Models.UserModels.TeacherUser", null)
                        .WithMany("Works")
                        .HasForeignKey("TeacherUserId");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Student", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Subject", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("SchoolHubApi.Models.SchoolModels.Teacher", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolHubApi.Models.UserModels.TeacherUser", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Schools");

                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
